const fs = require('fs');
const path = require('path');

const PRODUCTS_DATA = [
  // ── KITCHEN (20 items) ──
  {
    name: "Prestige Iris 750 Watt Mixer Grinder with 3 Stainless Steel Jars",
    brand: "Prestige",
    category: "Kitchen",
    rating: 4.3,
    ratingCount: 38420,
    price: 3299,
    originalPrice: 6295,
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=600&q=80",
    description: "Heavy-duty 750W copper motor with overload protection, 3 multipurpose stainless steel jars, and a transparent juicer jar.",
    bestFor: "Daily spice grinding, batters, and fresh juice extraction"
  },
  {
    name: "Hawkins Contura Hard Anodized 3 Litre Pressure Cooker",
    brand: "Hawkins",
    category: "Kitchen",
    rating: 4.5,
    ratingCount: 29150,
    price: 1875,
    originalPrice: 2200,
    image: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80",
    description: "Curved body for easy stirring, 60-micron hard anodised surface that does not react with acidic foods, and inside-fitting safety lid.",
    bestFor: "Fast everyday lentils, rice, and vegetable curries for small families"
  },
  {
    name: "Pigeon by Stovekraft 1.5L Stainless Steel Electric Kettle",
    brand: "Pigeon",
    category: "Kitchen",
    rating: 4.2,
    ratingCount: 64200,
    price: 649,
    originalPrice: 1245,
    image: "https://images.unsplash.com/photo-1594213114663-dd963b658ec5?auto=format&fit=crop&w=600&q=80",
    description: "1500W rapid boil kettle with 360-degree swivel base, auto shut-off safety sensor, and cool-touch ergonomic handle.",
    bestFor: "Instant morning tea, black coffee, and hot water preparation"
  },
  {
    name: "Philips Digital Air Fryer HD9200 with Rapid Air Technology",
    brand: "Philips",
    category: "Kitchen",
    rating: 4.5,
    ratingCount: 16890,
    price: 6999,
    originalPrice: 9995,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80",
    description: "Patented starfish design bottom distributes hot air evenly for crispy results with up to 90% less oil.",
    bestFor: "Guilt-free frying, roasting snacks, and reheating baked goods"
  },
  {
    name: "Prestige PIC 20 1600 Watt Induction Cooktop with Indian Menu",
    brand: "Prestige",
    category: "Kitchen",
    rating: 4.3,
    ratingCount: 24700,
    price: 2499,
    originalPrice: 3895,
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80",
    description: "Full glass ceramic surface with preset Indian cooking options (chapati, dosa, milk, curry) and automatic voltage regulator.",
    bestFor: "Flame-free countertop cooking and quick meal prep in modern apartments"
  },
  {
    name: "Milton Executive Stainless Steel Insulated Tiffin Box (3 Containers)",
    brand: "Milton",
    category: "Kitchen",
    rating: 4.4,
    ratingCount: 18230,
    price: 999,
    originalPrice: 1350,
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    description: "Double-walled vacuum insulated lunch carrier with leak-proof lids and thermal thermal bag keeping food warm for 6 hours.",
    bestFor: "Office lunches and hot homemade meals on the go"
  },
  {
    name: "Cello Checkers Modular Plastic Airtight Storage Containers (Set of 18)",
    brand: "Cello",
    category: "Kitchen",
    rating: 4.2,
    ratingCount: 14300,
    price: 849,
    originalPrice: 1599,
    image: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=600&q=80",
    description: "BPA-free 100% food grade containers with checkered texture for grip and airtight seal to keep spices and pulses moisture-free.",
    bestFor: "Organising pantry shelves, grains, pulses, and dry fruits"
  },
  {
    name: "Butterfly Jet 4 Jar 750W Mixer Grinder with Unbreakable Lids",
    brand: "Butterfly",
    category: "Kitchen",
    rating: 4.1,
    ratingCount: 11950,
    price: 2999,
    originalPrice: 5499,
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80",
    description: "Robust motor with ventilation technology, heavy-duty stainless steel blades, and dedicated juicer extractor.",
    bestFor: "South Indian batter grinding, chutneys, and coarse masalas"
  },
  {
    name: "Borosil Chef Delite 300W Hand Chopper with Twin Blades",
    brand: "Borosil",
    category: "Kitchen",
    rating: 4.4,
    ratingCount: 9480,
    price: 1449,
    originalPrice: 2090,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
    description: "One-touch electric vegetable chopper with stainless steel dual-blade set and 600ml break-resistant bowl.",
    bestFor: "Fine onion, garlic, nuts, and herb chopping in seconds"
  },
  {
    name: "Wonderchef Nutri-blend 400W Mixer Grinder & Smoothie Blender",
    brand: "Wonderchef",
    category: "Kitchen",
    rating: 4.3,
    ratingCount: 28300,
    price: 2799,
    originalPrice: 5000,
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80",
    description: "Compact 22,000 RPM super-fast extraction motor with surgical grade steel blades and bullet-style drinking cups.",
    bestFor: "Morning protein shakes, green smoothies, and dry spice blends"
  },
  {
    name: "Vinod Platinum Triply Stainless Steel Kadai with Stainless Steel Lid 2.5L",
    brand: "Vinod",
    category: "Kitchen",
    rating: 4.6,
    ratingCount: 5120,
    price: 2190,
    originalPrice: 3100,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=600&q=80",
    description: "Three-layer SAS construction (304 steel, aluminium core, magnetic 430 steel) ensuring zero hot spots and lifetime durability.",
    bestFor: "Deep frying, sautéing gravies, and Indian curries without burning"
  },
  {
    name: "Solimo Stainless Steel Induction Bottom Cookware Set (3 Pieces)",
    brand: "Solimo",
    category: "Kitchen",
    rating: 4.2,
    ratingCount: 16400,
    price: 1899,
    originalPrice: 3500,
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=600&q=80",
    description: "Includes fry pan, kadai with glass lid, and sauce pan with induction compatible sandwich bottoms.",
    bestFor: "Starter kitchen cookware for first-time home buyers and tenants"
  },
  {
    name: "Bajaj ATX 4 750W 2-Slice Pop-Up Toaster with Dust Cover",
    brand: "Bajaj",
    category: "Kitchen",
    rating: 4.2,
    ratingCount: 13800,
    price: 1399,
    originalPrice: 2125,
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=600&q=80",
    description: "6 browning level settings with mid-cycle cancel button, removable crumb tray, and cool touch body.",
    bestFor: "Crispy breakfast bread toast and quick bagels"
  },
  {
    name: "Milton Aqua 1000 Stainless Steel Water Bottle 1 Litre (Pack of 2)",
    brand: "Milton",
    category: "Kitchen",
    rating: 4.3,
    ratingCount: 22100,
    price: 599,
    originalPrice: 860,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    description: "Single wall grade 304 rust-proof stainless steel bottle with leak-proof screw cap.",
    bestFor: "Refrigerator water storage, gym workouts, and study desks"
  },
  {
    name: "Signoraware Modular Spice Box 7 Compartment Masala Dabba",
    brand: "Signoraware",
    category: "Kitchen",
    rating: 4.4,
    ratingCount: 7850,
    price: 349,
    originalPrice: 550,
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    description: "Food-safe BPA-free circular spice container with airtight transparent lid and included measuring spoon.",
    bestFor: "Keeping daily cooking spices fresh and within easy reach"
  },
  {
    name: "Kuber Industries Multipurpose Sink Dish Drainer Drying Rack",
    brand: "Kuber Industries",
    category: "Kitchen",
    rating: 4.3,
    ratingCount: 11200,
    price: 499,
    originalPrice: 1199,
    image: "https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&w=600&q=80",
    description: "Heavy-duty plastic dish organizer with utensil basket and sloped water drainage tray.",
    bestFor: "Drying plates, bowls, and cutlery near kitchen sink"
  },
  {
    name: "Kent Ultra Storage 7L UV and UF Water Purifier for Municipal Water",
    brand: "Kent",
    category: "Kitchen",
    rating: 4.1,
    ratingCount: 8900,
    price: 7499,
    originalPrice: 10500,
    image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=600&q=80",
    description: "Double purification with UV followed by hollow fibre UF membrane, suitable for low TDS tap water.",
    bestFor: "Safe drinking water disinfection in city apartments"
  },
  {
    name: "Prestige Omega Deluxe Granite 3-Piece Non-Stick Cookware Set",
    brand: "Prestige",
    category: "Kitchen",
    rating: 4.3,
    ratingCount: 26500,
    price: 2499,
    originalPrice: 4880,
    image: "https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?auto=format&fit=crop&w=600&q=80",
    description: "5-layer scratch resistant granite non-stick coating with induction bottom and dishwasher safety.",
    bestFor: "Low oil dosas, omelettes, and delicate pancake cooking"
  },
  {
    name: "Borosil Klip N Store Microwave Safe Glass Container Set (Pack of 3)",
    brand: "Borosil",
    category: "Kitchen",
    rating: 4.5,
    ratingCount: 15400,
    price: 1199,
    originalPrice: 1690,
    image: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=600&q=80",
    description: "100% borosilicate glass that withstands temperatures up to 400°C; safe for microwave, oven, and freezer.",
    bestFor: "Reheating curries without plastic leach and storing leftovers safely"
  },
  {
    name: "Ganesh Multipurpose Vegetable and Fruit Quick Chopper Cutter",
    brand: "Ganesh",
    category: "Kitchen",
    rating: 4.2,
    ratingCount: 19800,
    price: 349,
    originalPrice: 799,
    image: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&w=600&q=80",
    description: "Manual pull-cord string chopper with three angled Japanese stainless steel blades and anti-skid silicone base.",
    bestFor: "Quick salad prep, salsa, and tearless onion cutting without electricity"
  },

  // ── CLEANING (16 items) ──
  {
    name: "Scotch-Brite 2-in-1 Bucket Spin Mop with Microfibre Refills",
    brand: "Scotch-Brite",
    category: "Cleaning",
    rating: 4.3,
    ratingCount: 31200,
    price: 1499,
    originalPrice: 2200,
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&q=80",
    description: "Twin bucket mechanism with separate wash and dry chambers, 360-degree telescopic stainless steel handle, and ultra-absorbent microfibre head.",
    bestFor: "Effortless wet mopping across marble, vitrified tiles, and wooden floors"
  },
  {
    name: "Eureka Forbes Quick Clean DX 1200W Canister Vacuum Cleaner",
    brand: "Eureka Forbes",
    category: "Cleaning",
    rating: 4.2,
    ratingCount: 19400,
    price: 3999,
    originalPrice: 5999,
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=600&q=80",
    description: "Powerful 1200W suction with dust bag full indicator, automatic cord winder, and versatile attachments for sofa crevice cleaning.",
    bestFor: "Deep sofa dusting, carpet vacuuming, and curtain maintenance"
  },
  {
    name: "SOFTSPUN Microfibre Cleaning Cloths 340 GSM (Pack of 5)",
    brand: "SOFTSPUN",
    category: "Cleaning",
    rating: 4.5,
    ratingCount: 42100,
    price: 329,
    originalPrice: 650,
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=600&q=80",
    description: "High density plush microfibre that traps fine dust, grease, and water droplets without scratching sensitive surfaces.",
    bestFor: "TV screens, kitchen slabs, car interiors, and bathroom mirrors"
  },
  {
    name: "Spotzero by Milton Zero Dust Plastic Broom with Extendable Handle",
    brand: "Spotzero",
    category: "Cleaning",
    rating: 4.3,
    ratingCount: 26800,
    price: 299,
    originalPrice: 499,
    image: "https://images.unsplash.com/photo-1585670270608-b404fb88e224?auto=format&fit=crop&w=600&q=80",
    description: "Synthetically engineered micro-bristles that pick up fine sand and hair without shedding natural broom grass or bhusa.",
    bestFor: "Indoor floor sweeping without leaving yellow broom dust"
  },
  {
    name: "Kuber Industries Heavy Duty Plastic Pedal Dustbin 12 Litre",
    brand: "Kuber Industries",
    category: "Cleaning",
    rating: 4.2,
    ratingCount: 7600,
    price: 499,
    originalPrice: 899,
    image: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=600&q=80",
    description: "Hands-free foot pedal trash can with inner removable bucket for hygienic garbage disposal in kitchens and restrooms.",
    bestFor: "Kitchen dry/wet waste segregation and bathroom waste"
  },
  {
    name: "Gala Double Lip Bathroom Floor Wiper with Long Handle",
    brand: "Gala",
    category: "Cleaning",
    rating: 4.3,
    ratingCount: 14200,
    price: 249,
    originalPrice: 399,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Dual rubber lip that pulls stagnant shower water instantly off ceramic tiles, leaving floors dry and skid-free.",
    bestFor: "Quick bathroom drying after showers to prevent mould and slips"
  },
  {
    name: "Scotch-Brite Heavy Duty Kitchen Scrub Sponge (Pack of 6)",
    brand: "Scotch-Brite",
    category: "Cleaning",
    rating: 4.5,
    ratingCount: 33800,
    price: 199,
    originalPrice: 270,
    image: "https://images.unsplash.com/photo-1585670270608-b404fb88e224?auto=format&fit=crop&w=600&q=80",
    description: "Dual-action cleaning pad with tough abrasive green scrubber on one side and absorbent yellow sponge on reverse.",
    bestFor: "Washing burnt oil utensils, stainless steel plates, and glassware"
  },
  {
    name: "Cello Classic Plastic Laundry Basket with Lid 50 Litre",
    brand: "Cello",
    category: "Cleaning",
    rating: 4.3,
    ratingCount: 11400,
    price: 799,
    originalPrice: 1299,
    image: "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=600&q=80",
    description: "Ventilated weave plastic construction preventing damp odour with click-lock lid and side carry grips.",
    bestFor: "Holding dirty family clothes next to the washing machine"
  },
  {
    name: "Inalsa Cordless Handheld Car & Home Vacuum Cleaner 8000PA",
    brand: "Inalsa",
    category: "Cleaning",
    rating: 4.1,
    ratingCount: 8200,
    price: 1899,
    originalPrice: 3995,
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=600&q=80",
    description: "Rechargeable lithium battery vacuum with washable HEPA filter and slim crevice nozzle.",
    bestFor: "Car seat dust, computer keyboards, and quick crumbs cleanup"
  },
  {
    name: "Scotch-Brite Toilet Plunger and Heavy Duty Rim Brush Set",
    brand: "Scotch-Brite",
    category: "Cleaning",
    rating: 4.4,
    ratingCount: 16200,
    price: 449,
    originalPrice: 650,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Angular curved bristles to reach under Western toilet bowl rims, combined with durable storage caddy.",
    bestFor: "Hygienic toilet sanitization and stain removal"
  },
  {
    name: "Gala Iron Stand with Rust-Proof Aluminium Cloth Drying Rack",
    brand: "Gala",
    category: "Cleaning",
    rating: 4.2,
    ratingCount: 6900,
    price: 1699,
    originalPrice: 2999,
    image: "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=600&q=80",
    description: "Foldable multi-tier laundry drying stand with 55 feet of drying space, shoe drying brackets, and caster wheels.",
    bestFor: "Indoor clothes drying during monsoons and balcony spaces"
  },
  {
    name: "Plantex Stainless Steel Wall Mounted Kitchen Paper Towel Dispenser",
    brand: "Plantex",
    category: "Cleaning",
    rating: 4.4,
    ratingCount: 4800,
    price: 649,
    originalPrice: 1199,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Anti-rust stainless steel chrome finish dispenser for tissue paper rolls and aluminium foil.",
    bestFor: "Clean countertop maintenance and hands-free tissue tearing"
  },
  {
    name: "Dettol Disinfectant Multi-Surface Cleaning Spray (500ml Pack of 2)",
    brand: "Dettol",
    category: "Cleaning",
    rating: 4.6,
    ratingCount: 22400,
    price: 349,
    originalPrice: 420,
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=600&q=80",
    description: "Hospital grade surface spray kills 99.9% germs, leaves a mild fresh citrus scent, and cuts cooking grease.",
    bestFor: "Sanitising door handles, dining tables, kitchen slabs, and packages"
  },
  {
    name: "Gala Stainless Steel Scrub Sponge Pad for Utensils (Pack of 8)",
    brand: "Gala",
    category: "Cleaning",
    rating: 4.3,
    ratingCount: 15300,
    price: 189,
    originalPrice: 280,
    image: "https://images.unsplash.com/photo-1585670270608-b404fb88e224?auto=format&fit=crop&w=600&q=80",
    description: "High-grade curled wire mesh that scrubs tough charred food from cast iron and aluminium without cutting fingers.",
    bestFor: "Scouring heavy milk pots, tawa crusts, and barbecue grates"
  },
  {
    name: "Prestige CleanHome Magic Sponge Stain Eraser (Pack of 10)",
    brand: "Prestige",
    category: "Cleaning",
    rating: 4.2,
    ratingCount: 7100,
    price: 299,
    originalPrice: 599,
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=600&q=80",
    description: "Melamine foam micro-abrasive sponge that lifts crayon marks, tea stains, and wall scuffs using just water.",
    bestFor: "Cleaning dirty light switches, white walls, and bathroom grout"
  },
  {
    name: "Spotzero by Milton Telescopic High-Reach Cobweb Duster",
    brand: "Spotzero",
    category: "Cleaning",
    rating: 4.3,
    ratingCount: 10400,
    price: 499,
    originalPrice: 850,
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&q=80",
    description: "Extendable pole reaching up to 10 feet with electrostatic rounded brush head that captures cobwebs effortlessly.",
    bestFor: "Cleaning high ceiling corners, ceiling fans, and chandelier edges"
  },

  // ── HOME & ORGANISERS (16 items) ──
  {
    name: "DeckUp Plank Engineered Wood 3-Door Shoe Rack with Seat",
    brand: "DeckUp",
    category: "Home",
    rating: 4.2,
    ratingCount: 8900,
    price: 4299,
    originalPrice: 7500,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Dark walnut finish engineered wood cabinet holding 12 pairs of footwear with cushioned top bench for sitting.",
    bestFor: "Entryway shoe storage and modern hallway decor"
  },
  {
    name: "Wipro Coral Rechargeable Emergency LED Lantern 360 Light",
    brand: "Wipro",
    category: "Home",
    rating: 4.3,
    ratingCount: 17600,
    price: 1199,
    originalPrice: 1990,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
    description: "84 bright LED beads with rotary dimmer control and built-in 3000mAh battery providing up to 15 hours of backup.",
    bestFor: "Power cuts, balcony reading, and emergency light source"
  },
  {
    name: "GM Modular G-Power 4+1 Power Strip Extension Cord with Spike Guard",
    brand: "GM Modular",
    category: "Home",
    rating: 4.4,
    ratingCount: 31200,
    price: 499,
    originalPrice: 850,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "Fire-retardant plastic board with 4 universal sockets, master switch, surge protection fuse, and 2-metre copper cable.",
    bestFor: "Work-from-home desk setups, TV consoles, and mobile charging stations"
  },
  {
    name: "Solimo 4-Tier Multipurpose Metal Utility Storage Rolling Cart",
    brand: "Solimo",
    category: "Home",
    rating: 4.4,
    ratingCount: 12400,
    price: 1699,
    originalPrice: 2800,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Powder-coated steel mesh wire baskets with 360-degree swivel wheels and brakes for tight space storage.",
    bestFor: "Kitchen vegetable rack, bathroom toiletries, and nursery essentials"
  },
  {
    name: "AmazonBasics Heavy Duty Steel Foldable 3-Step Ladder with Anti-Slip Steps",
    brand: "AmazonBasics",
    category: "Home",
    rating: 4.5,
    ratingCount: 9800,
    price: 2299,
    originalPrice: 3800,
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80",
    description: "Supports up to 150 kg with extra-wide rubber ribbed steps and cushioned handrail for safe balance.",
    bestFor: "Reaching loft storage, cleaning fans, and hanging curtains"
  },
  {
    name: "Spaces Solid 100% Cotton 210 TC Double Bed Sheet with 2 Pillow Covers",
    brand: "Spaces",
    category: "Home",
    rating: 4.3,
    ratingCount: 15300,
    price: 1299,
    originalPrice: 2199,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80",
    description: "Breathable combed cotton with colour-lock technology, skin-friendly texture, and fade resistance after multiple washes.",
    bestFor: "Master bedroom aesthetic and comfortable summer sleep"
  },
  {
    name: "Cortina Blackout Eyelet Window & Door Curtains (Set of 2 Panels)",
    brand: "Cortina",
    category: "Home",
    rating: 4.2,
    ratingCount: 21400,
    price: 899,
    originalPrice: 1999,
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80",
    description: "Triple weave polyester fabric blocks 85% sunlight, reduces outside street noise, and provides total room privacy.",
    bestFor: "Living room TV glare protection and bedroom afternoon naps"
  },
  {
    name: "Story@Home Anti-Skid Microfibre Soft Water Absorbent Door Mat (Set of 2)",
    brand: "Story@Home",
    category: "Home",
    rating: 4.4,
    ratingCount: 18900,
    price: 399,
    originalPrice: 899,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Ultra-soft microfibre plush pile with non-slip thermoplastic latex backing that grips ceramic and marble flooring.",
    bestFor: "Main doorway entrance, bathroom door, and kitchen sink footboard"
  },
  {
    name: "Solimo Non-Ticking Silent Sweep Wall Clock 12-inch Rose Gold",
    brand: "Solimo",
    category: "Home",
    rating: 4.3,
    ratingCount: 13700,
    price: 649,
    originalPrice: 1200,
    image: "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=600&q=80",
    description: "Large bold numerals with silent quartz movement eliminating all ticking sounds in quiet study rooms.",
    bestFor: "Living room wall accent and peaceful bedroom timekeeping"
  },
  {
    name: "Godrej Locking Solutions Nav-Tal 6-Lever Brass Padlock with 3 Keys",
    brand: "Godrej",
    category: "Home",
    rating: 4.6,
    ratingCount: 34500,
    price: 499,
    originalPrice: 630,
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80",
    description: "Solid brass cylinder with rust-proof hardened steel shackle, drill-resistant design, and authentic dual keys.",
    bestFor: "Main gate security, locker protection, and vacation house lockups"
  },
  {
    name: "Homewell Wardrobe Hanging Storage Organizer 4 Shelves",
    brand: "Homewell",
    category: "Home",
    rating: 4.2,
    ratingCount: 8400,
    price: 449,
    originalPrice: 899,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Collapsible non-woven fabric organiser with reinforced heavy-duty cardboard inserts for tees and towels.",
    bestFor: "Maximising vertical cupboard space in compact apartments"
  },
  {
    name: "Wakefit Memory Foam Hollow Fibre Sleeping Pillow (Pack of 2)",
    brand: "Wakefit",
    category: "Home",
    rating: 4.4,
    ratingCount: 41200,
    price: 999,
    originalPrice: 1999,
    image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80",
    description: "Ergonomic neck support pillows filled with virgin microfiber that adjust height for side and back sleepers.",
    bestFor: "Preventing morning neck stiffness and deep sleep comfort"
  },
  {
    name: "Holicolor Waterproof Under-Bed Storage Bags with Clear Window (Pack of 3)",
    brand: "Holicolor",
    category: "Home",
    rating: 4.3,
    ratingCount: 6800,
    price: 599,
    originalPrice: 1299,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Durable Oxford cloth organizers with reinforced side handles and clear PVC viewing window.",
    bestFor: "Storing winter quilts, blankets, and excess bed linens dust-free"
  },
  {
    name: "Plantex Stainless Steel Bathroom Corner Shelf Rack (Set of 2)",
    brand: "Plantex",
    category: "Home",
    rating: 4.4,
    ratingCount: 14700,
    price: 749,
    originalPrice: 1499,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Grade 304 mirror chrome plated triangle shower caddy with drainage slots and screw-less adhesive hooks option.",
    bestFor: "Organizing shampoo bottles, body wash, and face cleansers"
  },
  {
    name: "Sehaz Art Works Key Holder for Wall Decor with 6 Metal Hooks",
    brand: "Sehaz Art",
    category: "Home",
    rating: 4.3,
    ratingCount: 9200,
    price: 349,
    originalPrice: 799,
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80",
    description: "Matte black laser cut metal key organiser with integrated letter rack for bills and envelopes.",
    bestFor: "Never misplacing car, bike, and apartment keys near the door"
  },
  {
    name: "Cushion Craft Premium Velvet Cushion Covers 16x16 inch (Set of 5)",
    brand: "Cushion Craft",
    category: "Home",
    rating: 4.4,
    ratingCount: 11100,
    price: 599,
    originalPrice: 1299,
    image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80",
    description: "Plush Dutch velvet fabric with concealed zipper seams and rich jewel-tone colourways.",
    bestFor: "Adding instant warmth and luxury texture to the living room couch"
  },

  // ── APPLIANCES (18 items) ──
  {
    name: "LG 185 L 5-Star Inverter Direct-Cool Single Door Refrigerator",
    brand: "LG",
    category: "Appliances",
    rating: 4.4,
    ratingCount: 22800,
    price: 16490,
    originalPrice: 22199,
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=600&q=80",
    description: "Smart Inverter Compressor for quiet operation, toughened glass shelves supporting up to 175kg, and fastest ice making.",
    bestFor: "Couples, bachelors, and 1-2 BHK apartment kitchens"
  },
  {
    name: "Samsung 7 kg Fully-Automatic Top Loading Washing Machine (WA70A4002GS)",
    brand: "Samsung",
    category: "Appliances",
    rating: 4.3,
    ratingCount: 31400,
    price: 15990,
    originalPrice: 21000,
    image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=600&q=80",
    description: "Diamond Drum design protects fabrics, Center Jet technology prevents tangles, and Magic Filter gathers lint.",
    bestFor: "Hassle-free daily laundry for families of 3-4 members"
  },
  {
    name: "Atomberg Renesa 1200mm BLDC Motor Ceiling Fan with Remote",
    brand: "Atomberg",
    category: "Appliances",
    rating: 4.5,
    ratingCount: 46200,
    price: 3699,
    originalPrice: 5190,
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=600&q=80",
    description: "Consumes only 28W at top speed, saving up to ₹1,500 every year on electricity bills; includes sleep timer and boost mode.",
    bestFor: "High airflow cooling with maximum power bill savings"
  },
  {
    name: "Bajaj New Shakti Neo 15L Vertical Water Heater Geyser (4 Star)",
    brand: "Bajaj",
    category: "Appliances",
    rating: 4.2,
    ratingCount: 16700,
    price: 5899,
    originalPrice: 9950,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Titanium armour technology with glassline inner tank, swirl flow technology for 20% more hot water, and 8 bar pressure rating.",
    bestFor: "High-rise apartment bathrooms with booster pressure pumps"
  },
  {
    name: "Philips GC181 Heavy Weight 1000W Dry Iron with Black American Heritage Soleplate",
    brand: "Philips",
    category: "Appliances",
    rating: 4.4,
    ratingCount: 35800,
    price: 1149,
    originalPrice: 1595,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "Heavy 1.6kg body provides ideal natural pressure on stubborn linen creases without tiring wrists.",
    bestFor: "Crisp cotton formal shirts and traditional Indian attire"
  },
  {
    name: "Symphony Diet 12T Personal Tower Air Cooler 12 Litres",
    brand: "Symphony",
    category: "Appliances",
    rating: 4.0,
    ratingCount: 14300,
    price: 5799,
    originalPrice: 7999,
    image: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=600&q=80",
    description: "Honeycomb cooling pads, i-Pure multi-stage air purification, and compact footprint with caster wheels.",
    bestFor: "Personal bedroom cooling during dry summer months"
  },
  {
    name: "IFB 24 L Convection Microwave Oven (24BC5 with 65 Auto Cook Menus)",
    brand: "IFB",
    category: "Appliances",
    rating: 4.3,
    ratingCount: 11200,
    price: 11490,
    originalPrice: 15990,
    image: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=600&q=80",
    description: "Disinfect function, multi-stage cooking, steam clean cavity, and stainless steel interior for uniform grilling.",
    bestFor: "Baking cakes, grilling paneer tikka, and quick defrosting"
  },
  {
    name: "Havells Calido 2000W PTC Ceramic Fan Room Heater",
    brand: "Havells",
    category: "Appliances",
    rating: 4.2,
    ratingCount: 8700,
    price: 3699,
    originalPrice: 5390,
    image: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=600&q=80",
    description: "Rapid ceramic heating with oscillation function, tip-over safety switch, and dust filter.",
    bestFor: "Winter warmth in bedrooms across North and Central India"
  },
  {
    name: "Crompton Ozone 75 Litres Desert Air Cooler with Everlast Pump",
    brand: "Crompton",
    category: "Appliances",
    rating: 4.1,
    ratingCount: 19800,
    price: 10499,
    originalPrice: 17200,
    image: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=600&q=80",
    description: "Woodwool cooling pads, 4-way air deflection, and inverter compatibility with large ice chamber.",
    bestFor: "Large living rooms and halls during hot summer days"
  },
  {
    name: "Mi Smart Air Purifier 4 with True HEPA Filter and App Control",
    brand: "Xiaomi",
    category: "Appliances",
    rating: 4.4,
    ratingCount: 13900,
    price: 13999,
    originalPrice: 19999,
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=600&q=80",
    description: "Filters 99.97% of 0.3 micron particles, real-time OLED PM2.5 monitor, and Alexa/Google voice integration.",
    bestFor: "Combatting city smog, dust allergies, and pet dander indoors"
  },
  {
    name: "Morphy Richards Europa 800W Espresso & Cappuccino Coffee Maker",
    brand: "Morphy Richards",
    category: "Appliances",
    rating: 4.1,
    ratingCount: 7800,
    price: 4499,
    originalPrice: 6595,
    image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=600&q=80",
    description: "Steam control knob with milk frother wand for rich cafe-style foam and temperature indicator dial.",
    bestFor: "Home barista espressos, lattes, and cappuccinos"
  },
  {
    name: "Whirlpool 240 L Frost Free Triple Door Refrigerator (Protton FP 263D)",
    brand: "Whirlpool",
    category: "Appliances",
    rating: 4.3,
    ratingCount: 18400,
    price: 26490,
    originalPrice: 34990,
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=600&q=80",
    description: "Dedicated bottom vegetable drawer with Active Fresh Zone preventing odour mixing between tiers.",
    bestFor: "Families desiring dedicated vegetable crisper and zero frost hassle"
  },
  {
    name: "Havells Glaze 750W 3-Jar Mixer Grinder with Copper Motor",
    brand: "Havells",
    category: "Appliances",
    rating: 4.3,
    ratingCount: 12600,
    price: 3499,
    originalPrice: 5995,
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=600&q=80",
    description: "304 grade stainless steel jars, ergonomic handles, dual exhaust cooling, and cord winder groove.",
    bestFor: "Heavy duty daily wet grinding and purees"
  },
  {
    name: "Orient Electric Stand-37 400mm Pedestal Fan with High Air Delivery",
    brand: "Orient",
    category: "Appliances",
    rating: 4.2,
    ratingCount: 9600,
    price: 2499,
    originalPrice: 3690,
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=600&q=80",
    description: "Aerodynamic resin blades, 90-degree smooth oscillation, and height adjustment mechanism with weighted base.",
    bestFor: "Balcony seating, dining areas, and portable air breeze"
  },
  {
    name: "Black+Decker 1400W High Pressure Washer Car & Home Cleaner",
    brand: "Black+Decker",
    category: "Appliances",
    rating: 4.3,
    ratingCount: 6500,
    price: 6899,
    originalPrice: 11000,
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=600&q=80",
    description: "110 Bar pressure with foam nozzle lance, 5-metre high pressure hose, and auto-stop safety system.",
    bestFor: "Car washing, patio tiles, exterior villa walls, and parking areas"
  },
  {
    name: "Bajaj Minor 1000W Radiant Room Heater with Nickel Chrome Mesh",
    brand: "Bajaj",
    category: "Appliances",
    rating: 4.1,
    ratingCount: 14800,
    price: 899,
    originalPrice: 1450,
    image: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=600&q=80",
    description: "Stainless steel reflector dish with instant radiant warmth and tip-over safety shut-off.",
    bestFor: "Instant personal spot heating on cold winter mornings"
  },
  {
    name: "Crompton Arno Neo 15-Litre 5-Star Storage Water Heater",
    brand: "Crompton",
    category: "Appliances",
    rating: 4.3,
    ratingCount: 28900,
    price: 6199,
    originalPrice: 10500,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Magnesium anode rod for hard water protection with superior glassline coated inner tank.",
    bestFor: "Hard water regions and high-rise apartments"
  },
  {
    name: "Morphy Richards Orbit 2000W Induction Cooktop with Touch Screen",
    brand: "Morphy Richards",
    category: "Appliances",
    rating: 4.3,
    ratingCount: 8400,
    price: 3199,
    originalPrice: 4895,
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80",
    description: "Sleek full surface touch panel with power boost mode, auto-pan detection, and 3-hour timer.",
    bestFor: "Modern kitchen countertops and precise temperature cooking"
  },

  // ── LIGHTING (10 items) ──
  {
    name: "Philips Smart Wi-Fi LED Bulb 9W B22 (16 Million Colours & Tunable White)",
    brand: "Philips",
    category: "Lighting",
    rating: 4.3,
    ratingCount: 38700,
    price: 699,
    originalPrice: 1999,
    image: "https://images.unsplash.com/photo-1550985616-10810253b84d?auto=format&fit=crop&w=600&q=80",
    description: "Controls via WiZ mobile app without extra bridge; schedules wake up sunrise modes and synchronises with music.",
    bestFor: "Smart bedroom mood lighting, party scenes, and voice control"
  },
  {
    name: "Wipro 10W B22 LED Warm White Bulbs (Pack of 4)",
    brand: "Wipro",
    category: "Lighting",
    rating: 4.4,
    ratingCount: 27900,
    price: 399,
    originalPrice: 796,
    image: "https://images.unsplash.com/photo-1532007271951-c487760934ae?auto=format&fit=crop&w=600&q=80",
    description: "High lumen output with 4kV surge protection and warm 2700K cozy glow that reduces eye fatigue.",
    bestFor: "Living room wall sconces, reading lamps, and bedside tables"
  },
  {
    name: "Murphy 12W Round LED Concealed Recessed Ceiling Downlight (Pack of 4)",
    brand: "Murphy",
    category: "Lighting",
    rating: 4.3,
    ratingCount: 11400,
    price: 849,
    originalPrice: 1799,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
    description: "Die-cast aluminium heat sink with ultra-slim rim and frosted diffuser preventing harsh glare.",
    bestFor: "False ceiling illumination in modern living and dining rooms"
  },
  {
    name: "Qubo Smart Plug 16A with Energy Monitoring (by Hero Group)",
    brand: "Qubo",
    category: "Lighting",
    rating: 4.2,
    ratingCount: 9200,
    price: 899,
    originalPrice: 1790,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "Transforms ordinary geysers, ACs, and motor pumps into smart devices controlled via smartphone timer.",
    bestFor: "Scheduling geyser heating and monitoring power consumption"
  },
  {
    name: "Govee Smart LED Strip Lights 5 Metre with App & Voice Control",
    brand: "Govee",
    category: "Lighting",
    rating: 4.5,
    ratingCount: 16400,
    price: 1899,
    originalPrice: 3200,
    image: "https://images.unsplash.com/photo-1550985616-10810253b84d?auto=format&fit=crop&w=600&q=80",
    description: "Flexible RGBIC tape with 3M adhesive backing, built-in microphone for sound sync, and dynamic segment control.",
    bestFor: "Behind TV backlighting, under-cabinet kitchen glow, and gaming desks"
  },
  {
    name: "Eveready Base B22 12W Inverter Emergency LED Bulb",
    brand: "Eveready",
    category: "Lighting",
    rating: 4.3,
    ratingCount: 22100,
    price: 349,
    originalPrice: 599,
    image: "https://images.unsplash.com/photo-1532007271951-c487760934ae?auto=format&fit=crop&w=600&q=80",
    description: "Built-in rechargeable 2200mAh Li-ion battery turns on automatically during power failure for up to 4 hours.",
    bestFor: "Uninterrupted lighting during unexpected power outages"
  },
  {
    name: "Home Centre Metal Table Lamp with Fabric Shade (Gold & White)",
    brand: "Home Centre",
    category: "Lighting",
    rating: 4.4,
    ratingCount: 5400,
    price: 1299,
    originalPrice: 2499,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
    description: "Brushed brass finished base with textured linen empire shade creating a gentle diffused glow.",
    bestFor: "Bedside nightstands and console table decor"
  },
  {
    name: "Philips Linear Hue Under-Cabinet 10W Warm White LED Batten Tube",
    brand: "Philips",
    category: "Lighting",
    rating: 4.4,
    ratingCount: 19800,
    price: 299,
    originalPrice: 450,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
    description: "Slim profile polycarbonate tube with wide 180-degree beam angle, high lumen efficiency, and flicker-free driver.",
    bestFor: "Kitchen counter task lighting and wardrobe interiors"
  },
  {
    name: "Syska Smart Motion Sensor LED Night Light with Magnetic Wall Mount",
    brand: "Syska",
    category: "Lighting",
    rating: 4.3,
    ratingCount: 8800,
    price: 499,
    originalPrice: 999,
    image: "https://images.unsplash.com/photo-1550985616-10810253b84d?auto=format&fit=crop&w=600&q=80",
    description: "PIR motion sensor detects movement up to 3 metres, lighting up warm LEDs automatically in darkness.",
    bestFor: "Hallway night navigation, stairs, and kid's bedrooms"
  },
  {
    name: "Havells Adore 6W LED Step Footlight for Staircases (Pack of 2)",
    brand: "Havells",
    category: "Lighting",
    rating: 4.4,
    ratingCount: 4200,
    price: 699,
    originalPrice: 1150,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
    description: "Recessed architectural wall luminaire with downward directed light beam preventing glare.",
    bestFor: "Duplex stairs, corridor foot paths, and pathway safety"
  },

  // ── TOOLS & HARDWARE (10 items) ──
  {
    name: "Bosch GSB 500W Professional Impact Drill Tool Kit (100 Accessories)",
    brand: "Bosch",
    category: "Tools",
    rating: 4.4,
    ratingCount: 29800,
    price: 4199,
    originalPrice: 6500,
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80",
    description: "Forward/reverse variable speed motor with hammer action, masonry drill bits, screws, anchors, claw hammer, and hard carrying case.",
    bestFor: "DIY wall picture hanging, shelf installations, and home repairs"
  },
  {
    name: "Stanley 10-Piece Cushion Grip Screwdriver Set (STMT66679)",
    brand: "Stanley",
    category: "Tools",
    rating: 4.5,
    ratingCount: 16700,
    price: 899,
    originalPrice: 1450,
    image: "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=600&q=80",
    description: "Chrome vanadium steel bars with magnetic black phosphate tips and comfortable tri-lobe ergonomic handles.",
    bestFor: "Tightening door hinges, electronic appliances, and toy battery compartments"
  },
  {
    name: "Taparia 8-inch Universal Combination Plier (1621-8)",
    brand: "Taparia",
    category: "Tools",
    rating: 4.6,
    ratingCount: 38200,
    price: 349,
    originalPrice: 480,
    image: "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=600&q=80",
    description: "Drop-forged high grade steel with induction hardened cutting edges and insulated non-slip handles.",
    bestFor: "Bending electrical wires, gripping stubborn nuts, and cutting cables"
  },
  {
    name: "Freemans 5 Metre Heavy Duty Compact Steel Measuring Tape",
    brand: "Freemans",
    category: "Tools",
    rating: 4.5,
    ratingCount: 21900,
    price: 249,
    originalPrice: 380,
    image: "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=600&q=80",
    description: "Nylon-coated durable yellow steel blade with true-zero hook, dual metric and imperial markings, and rubberised casing.",
    bestFor: "Measuring furniture dimensions, curtains, and room floor plans"
  },
  {
    name: "Black+Decker 12V Cordless Lithium-Ion Drill Driver with 10 Bits",
    brand: "Black+Decker",
    category: "Tools",
    rating: 4.3,
    ratingCount: 14600,
    price: 2699,
    originalPrice: 4500,
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80",
    description: "Keyless chuck with 11-position clutch torque settings and built-in LED worklight for dark cabinets.",
    bestFor: "Assembling flat-pack furniture, wood drilling, and screwing drywall"
  },
  {
    name: "Pidilite WD-40 Multipurpose Rust Prevention Spray 420ml",
    brand: "WD-40",
    category: "Tools",
    rating: 4.6,
    ratingCount: 48900,
    price: 389,
    originalPrice: 470,
    image: "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=600&q=80",
    description: "Penetrates seized rusted bolts, stops squeaky door hinges, drives out moisture, and dissolves sticky adhesive residue.",
    bestFor: "Silencing door squeaks, loosening jammed locks, and bike chain maintenance"
  },
  {
    name: "Stanley 16oz Steel Fiberglass Claw Hammer with Anti-Vibe Grip",
    brand: "Stanley",
    category: "Tools",
    rating: 4.5,
    ratingCount: 11200,
    price: 549,
    originalPrice: 850,
    image: "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=600&q=80",
    description: "Precision-balanced forged steel head with fiberglass handle that dampens shock vibrations by 40%.",
    bestFor: "Driving nails, pulling old wall plugs, and light carpentry"
  },
  {
    name: "Taparia 9-Piece Hex Allen Key Set (Metric 1.5mm to 10mm)",
    brand: "Taparia",
    category: "Tools",
    rating: 4.6,
    ratingCount: 24100,
    price: 299,
    originalPrice: 420,
    image: "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=600&q=80",
    description: "High tensile hardened steel with chamfered tips for smooth entry into hex fasteners.",
    bestFor: "Assembling study tables, bicycles, and office chairs"
  },
  {
    name: "Scotch Heavy Duty Outdoor Mounting Double Sided Tape (1 inch x 3 Metre)",
    brand: "Scotch",
    category: "Tools",
    rating: 4.4,
    ratingCount: 19800,
    price: 299,
    originalPrice: 450,
    image: "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=600&q=80",
    description: "Industrial strength 3M acrylic foam tape holding up to 6.8kg without drilling holes into wall tiles.",
    bestFor: "Hanging bathroom mirrors, nameplates, and routers without nails"
  },
  {
    name: "Stanley 8-inch Adjustable Chrome Vanadium Steel Spanner Wrench",
    brand: "Stanley",
    category: "Tools",
    rating: 4.5,
    ratingCount: 13400,
    price: 499,
    originalPrice: 780,
    image: "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=600&q=80",
    description: "Micro-smooth laser engraved knurl adjustment wheel with wide jaw capacity up to 29mm.",
    bestFor: "Plumbing repairs under washbasins and tightening water pipe taps"
  },

  // ── STORAGE & ORGANISATION (10 items) ──
  {
    name: "Spaces Vacuum Compression Storage Bags with Hand Pump (Set of 6)",
    brand: "Spaces",
    category: "Storage",
    rating: 4.3,
    ratingCount: 14700,
    price: 799,
    originalPrice: 1599,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Reduces volume by 80% with double-zip seal and triple-seal turbo valve keeping moisture and moths away.",
    bestFor: "Packing heavy winter blankets and expanding wardrobe capacity"
  },
  {
    name: "Solimo Foldable Fabric Storage Cubes with Handles (Pack of 3)",
    brand: "Solimo",
    category: "Storage",
    rating: 4.4,
    ratingCount: 18900,
    price: 599,
    originalPrice: 1199,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Reinforced non-woven fabric storage bins that fit standard cube shelving units like Ikea Kallax.",
    bestFor: "Tidying children's toys, books, folded t-shirts, and socks"
  },
  {
    name: "Kuber Industries Multipurpose Undergarment Drawer Organiser (Set of 3)",
    brand: "Kuber Industries",
    category: "Storage",
    rating: 4.3,
    ratingCount: 12200,
    price: 349,
    originalPrice: 699,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Divided compartmental organizers for ties, socks, handkerchiefs, and innerwear.",
    bestFor: "Keeping bedroom dresser drawers neat and clutter-free"
  },
  {
    name: "DeckUp Versatile 5-Tier Engineered Wood Corner Book Shelf",
    brand: "DeckUp",
    category: "Storage",
    rating: 4.2,
    ratingCount: 6800,
    price: 2499,
    originalPrice: 4500,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Zigzag floating corner display shelves with rich wenge laminate finish.",
    bestFor: "Showcasing trophies, potted succulents, and novels in unused room corners"
  },
  {
    name: "Cello Maxfresh Plastic Airtight Food Storage Jars (Pack of 6, 1200ml)",
    brand: "Cello",
    category: "Storage",
    rating: 4.4,
    ratingCount: 16300,
    price: 649,
    originalPrice: 1100,
    image: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=600&q=80",
    description: "Silicone ring gasket seal preserves crispness of biscuits, cereals, and dry namkeen.",
    bestFor: "Kitchen counter jar storage and breakfast cereals"
  },
  {
    name: "PrettyKrafts Wardrobe Saree Cover Bags with Front Zip (Set of 12)",
    brand: "PrettyKrafts",
    category: "Storage",
    rating: 4.3,
    ratingCount: 9400,
    price: 499,
    originalPrice: 999,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Breathable non-woven fabric with transparent top window protecting silk sarees from moisture and dust.",
    bestFor: "Festive saree, lehenga, and expensive suit preservation"
  },
  {
    name: "Homewell Stainless Steel Over-The-Door 6-Peg Towel & Robe Coat Hook",
    brand: "Homewell",
    category: "Storage",
    rating: 4.4,
    ratingCount: 11800,
    price: 299,
    originalPrice: 599,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Slips easily over any standard bedroom or bathroom door with zero screws or drilling required.",
    bestFor: "Hanging bathrobes, jackets, towels, and backpacks behind doors"
  },
  {
    name: "Kuber Industries Non-Woven Foldable Shoe Rack 4-Shelf Storage Unit",
    brand: "Kuber Industries",
    category: "Storage",
    rating: 4.1,
    ratingCount: 15400,
    price: 549,
    originalPrice: 1199,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Metal pipe frame with dust-proof zippered cover keeping footwear safe from moisture and dust.",
    bestFor: "Apartment corridors and temporary rental storage"
  },
  {
    name: "AmazonBasics Plastic Velvet Heavy Duty Non-Slip Clothes Hangers (Set of 30)",
    brand: "AmazonBasics",
    category: "Storage",
    rating: 4.5,
    ratingCount: 31200,
    price: 999,
    originalPrice: 1699,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Ultra-slim 0.5cm profile doubles wardrobe rail capacity with non-slip velvet surface that prevents clothes sliding off.",
    bestFor: "Hanging silk shirts, dresses, suits, and coats without shoulder bumps"
  },
  {
    name: "Solimo Modular 3-Tier Plastic Multipurpose Trolley with Wheels",
    brand: "Solimo",
    category: "Storage",
    rating: 4.3,
    ratingCount: 13200,
    price: 799,
    originalPrice: 1499,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Lightweight snap-together durable plastic cart with easy glide wheels.",
    bestFor: "Narrow bathroom spaces, onions/potatoes storage, and bedside utility"
  },

  // ── BATHROOM (10 items) ──
  {
    name: "Plantex Premium Stainless Steel Wall Mounted Towel Rack with Swivel Bars",
    brand: "Plantex",
    category: "Bathroom",
    rating: 4.4,
    ratingCount: 12600,
    price: 1199,
    originalPrice: 2400,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Foldable top shelf with 4 swivel bars and 4 lower hooks in high mirror polish finish.",
    bestFor: "Holding dry bath towels, fresh clothes, and loofahs"
  },
  {
    name: "Kohler Rain Duet Multifunction Hand Shower with 1.5M Hose",
    brand: "Kohler",
    category: "Bathroom",
    rating: 4.5,
    ratingCount: 8400,
    price: 1799,
    originalPrice: 2600,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "3 spray modes (Katalyst air-induction spray, massage stream, and gentle mist) with silicone nozzles that resist limescale.",
    bestFor: "Invigorating shower experience and easy tile rinsing"
  },
  {
    name: "Holicolor Automatic Infrared Touchless Liquid Soap Dispenser 400ml",
    brand: "Holicolor",
    category: "Bathroom",
    rating: 4.2,
    ratingCount: 6300,
    price: 699,
    originalPrice: 1499,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Motion sensor detects hands in 0.2 seconds, dispensing controlled soap drops without touching germy pump heads.",
    bestFor: "Hygienic handwashing in family bathrooms and kitchen sinks"
  },
  {
    name: "Saral Home Memory Foam Super Soft Embossed Bathroom Floor Mat",
    brand: "Saral Home",
    category: "Bathroom",
    rating: 4.4,
    ratingCount: 16800,
    price: 349,
    originalPrice: 799,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Quick-drying memory foam core with waffle fleece top and anti-skid rubber backing.",
    bestFor: "Stepping out of the shower without wetting the dry zone"
  },
  {
    name: "Plantex Stainless Steel Health Faucet Spray with 1 Metre Flexible Hose",
    brand: "Plantex",
    category: "Bathroom",
    rating: 4.3,
    ratingCount: 22400,
    price: 549,
    originalPrice: 1199,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Brass internal cartridge with high pressure burst-proof EPDM braided stainless steel hose.",
    bestFor: "Long-lasting toilet personal hygiene with zero drip leakage"
  },
  {
    name: "Solimo Ceramic 3-Piece Bathroom Set (Soap Dispenser, Tumbler, Soap Dish)",
    brand: "Solimo",
    category: "Bathroom",
    rating: 4.3,
    ratingCount: 7900,
    price: 649,
    originalPrice: 1299,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Glazed ceramic finish with rust-proof pump for handwash, toothbrush holder tumbler, and ribbed soap dish.",
    bestFor: "Upgrading washbasin vanity aesthetics"
  },
  {
    name: "Prestige CleanHome Automatic Toilet Rim Block Cleaner (Pack of 3)",
    brand: "Prestige",
    category: "Bathroom",
    rating: 4.2,
    ratingCount: 14100,
    price: 249,
    originalPrice: 375,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Hangs securely inside the toilet rim, releasing foaming detergent and fresh pine fragrance with every flush.",
    bestFor: "Continuous toilet freshness and preventing limescale build-up"
  },
  {
    name: "Plantex Heavy Duty Stainless Steel Double Robe Wall Hooks (Pack of 4)",
    brand: "Plantex",
    category: "Bathroom",
    rating: 4.5,
    ratingCount: 11200,
    price: 399,
    originalPrice: 850,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Concealed screw mounting with smooth curved prong edges that won't tear damp towels.",
    bestFor: "Hanging loofahs, face towels, and clothes in bathroom cubicles"
  },
  {
    name: "Cello Venice Translucent Plastic Bathroom Bucket and Mug Set 20L",
    brand: "Cello",
    category: "Bathroom",
    rating: 4.4,
    ratingCount: 19800,
    price: 499,
    originalPrice: 899,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Virgin food grade plastic bucket with strong ergonomic handle and graduated matching 1L bathing mug.",
    bestFor: "Traditional bucket bathing and household water storage"
  },
  // ── ADDITIONAL ESSENTIAL PRODUCTS TO REACH 108+ (34 items) ──
  {
    name: "Pigeon Sheen 4-Burner Glass Top Gas Stove with Brass Burners",
    brand: "Pigeon",
    category: "Kitchen",
    rating: 4.1,
    ratingCount: 16500,
    price: 3699,
    originalPrice: 7995,
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80",
    description: "Toughened black glass cooktop with heavy-duty brass burners and powder-coated steel pan supports.",
    bestFor: "Simultaneous multi-dish cooking for joint and large families"
  },
  {
    name: "Prestige Nakshatra Plus Hard Anodised Handi 5 Litre Pressure Cooker",
    brand: "Prestige",
    category: "Kitchen",
    rating: 4.4,
    ratingCount: 14200,
    price: 2399,
    originalPrice: 3200,
    image: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80",
    description: "Traditional handi shape with induction base, pressure indicator, and controlled gasket release system.",
    bestFor: "Biryanis, pulav, slow-simmered gravies, and large family meals"
  },
  {
    name: "Kent Instant 360W Egg Boiler with 3 Boiling Modes (7 Eggs)",
    brand: "Kent",
    category: "Kitchen",
    rating: 4.3,
    ratingCount: 19400,
    price: 1199,
    originalPrice: 1800,
    image: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80",
    description: "One-touch electric egg cooker with flat heating plate, water measuring cup with piercing pin, and auto shut-off.",
    bestFor: "Perfect soft, medium, or hard-boiled morning breakfast eggs"
  },
  {
    name: "Lifelong LLSM115G 750W Sandwich Griller and Toasting Maker",
    brand: "Lifelong",
    category: "Kitchen",
    rating: 4.1,
    ratingCount: 22800,
    price: 999,
    originalPrice: 1999,
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=600&q=80",
    description: "Non-stick grill plates with cool-touch body, power indicators, and compact upright storage latch.",
    bestFor: "Crispy grilled cheese sandwiches and panini snacks"
  },
  {
    name: "Milton Thermosteel Flip Lid 1000ml Vacuum Insulated Flask",
    brand: "Milton",
    category: "Kitchen",
    rating: 4.5,
    ratingCount: 52100,
    price: 1049,
    originalPrice: 1460,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    description: "Double wall vacuum insulation with copper coating keeps hot tea hot for 24 hours and iced drinks cold for 24 hours.",
    bestFor: "Long road journeys, hospital visits, and bedside hot water"
  },
  {
    name: "Tupperware Aquasafe 1000ml Round Water Bottles (Set of 4)",
    brand: "Tupperware",
    category: "Kitchen",
    rating: 4.4,
    ratingCount: 26300,
    price: 1149,
    originalPrice: 1550,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    description: "100% virgin food grade plastic with tab on flip-cap for easy opening and ergonomic contoured grip.",
    bestFor: "Refrigerator door storage and family dining table hydration"
  },
  {
    name: "Cello Grip Ergonomic Plastic Kitchen Chopping Board with Juice Groove",
    brand: "Cello",
    category: "Kitchen",
    rating: 4.3,
    ratingCount: 13700,
    price: 349,
    originalPrice: 650,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
    description: "Knife-friendly textured surface with anti-skid rubber feet and juice drip reservoir.",
    bestFor: "Daily fruit slicing, vegetable dicing, and meat trimming"
  },
  {
    name: "Harpic Power Plus 1 Litre Disinfectant Toilet Cleaner (Pack of 2)",
    brand: "Harpic",
    category: "Cleaning",
    rating: 4.6,
    ratingCount: 68400,
    price: 369,
    originalPrice: 440,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "10x better stain removal formula dissolves yellowish limescale and kills 99.9% toilet germs.",
    bestFor: "Deep weekly Western and Indian toilet bowl disinfection"
  },
  {
    name: "Colin Glass and Household Surface Cleaner Spray 500ml (Pack of 2)",
    brand: "Colin",
    category: "Cleaning",
    rating: 4.5,
    ratingCount: 47200,
    price: 219,
    originalPrice: 260,
    image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=600&q=80",
    description: "Shine boosters cut finger oil and dust on glass with streak-free drying and fresh floral scent.",
    bestFor: "Glass windows, bathroom mirrors, glass dining tables, and ovens"
  },
  {
    name: "Scotch-Brite Reusable Lint Roller with Handle (60 Sticky Sheets)",
    brand: "Scotch-Brite",
    category: "Cleaning",
    rating: 4.3,
    ratingCount: 16800,
    price: 299,
    originalPrice: 420,
    image: "https://images.unsplash.com/photo-1585670270608-b404fb88e224?auto=format&fit=crop&w=600&q=80",
    description: "High-tack adhesive tape picks up pet cat/dog hair, lint, and fluff from dark blazers and sofa fabric.",
    bestFor: "Formal black suit maintenance and pet owners"
  },
  {
    name: "Gala Tile and Floor Scrubber Brush with Ergonomic Handle",
    brand: "Gala",
    category: "Cleaning",
    rating: 4.4,
    ratingCount: 11900,
    price: 199,
    originalPrice: 320,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Pointed nose bristles that scrub grout lines, corners, and balcony stains without scratching tile glaze.",
    bestFor: "Hard scrub cleaning in wet bathroom corners and utility areas"
  },
  {
    name: "Spotzero by Milton Multipurpose Window Wiper Squeegee",
    brand: "Spotzero",
    category: "Cleaning",
    rating: 4.2,
    ratingCount: 14500,
    price: 249,
    originalPrice: 450,
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&q=80",
    description: "Dual head with microfibre washer sponge on one side and streak-free rubber squeegee on the other.",
    bestFor: "Cleaning high glass window panes and car windscreens"
  },
  {
    name: "Godrej Forte 15 Litre Electronic Digital Safety Security Locker",
    brand: "Godrej",
    category: "Home",
    rating: 4.4,
    ratingCount: 8900,
    price: 9499,
    originalPrice: 14500,
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80",
    description: "Motorised shooting bolts, digital PIN access with freeze lock after 3 incorrect attempts, and emergency override master key.",
    bestFor: "Safeguarding property documents, jewellery, and cash in wardrobes"
  },
  {
    name: "Solimo Anti-Vibration Noise Reduction Pads for Washing Machine (Set of 4)",
    brand: "Solimo",
    category: "Home",
    rating: 4.2,
    ratingCount: 15400,
    price: 349,
    originalPrice: 699,
    image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=600&q=80",
    description: "Heavy-duty tyre-grade rubber pads that absorb spin-cycle vibrations and stop washing machines from walking.",
    bestFor: "Silent washing machine operation on slick ceramic tiles"
  },
  {
    name: "Cello Multi-Shelf Plastic Bathroom & Kitchen Wall Cabinet with Mirror",
    brand: "Cello",
    category: "Home",
    rating: 4.3,
    ratingCount: 12100,
    price: 1499,
    originalPrice: 2499,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "High grade plastic cabinet with clear Belgian glass mirror, 4 internal compartments, and magnetic catch door.",
    bestFor: "Storing daily toiletries, grooming kits, and medicines safely"
  },
  {
    name: "Home Centre Ceramic Planter with Wooden Stand (Set of 2)",
    brand: "Home Centre",
    category: "Home",
    rating: 4.4,
    ratingCount: 6700,
    price: 899,
    originalPrice: 1799,
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80",
    description: "Matte glazed white ceramic pots with drainage holes and solid rubberwood tripods.",
    bestFor: "Indoor snake plants, money plants, and balcony greens"
  },
  {
    name: "Prestige PGMFB 800W Toast & Grill Sandwich Toaster",
    brand: "Prestige",
    category: "Appliances",
    rating: 4.2,
    ratingCount: 23100,
    price: 1399,
    originalPrice: 2095,
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=600&q=80",
    description: "Fixed grill plates coated with German non-stick technology for less butter toasting.",
    bestFor: "Warm breakfast toasts and quick evening snacks"
  },
  {
    name: "Bajaj Splendora 3 Litre 3kW Instant Water Heater Geyser",
    brand: "Bajaj",
    category: "Appliances",
    rating: 4.3,
    ratingCount: 19800,
    price: 2799,
    originalPrice: 5120,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Compact ABS rust-proof body with copper heating element and neon hot water indicators.",
    bestFor: "Instant hot water in kitchen sinks and guest washrooms"
  },
  {
    name: "Kent Table Top Vegetable and Fruit Cleaner Ozone Disinfectant",
    brand: "Kent",
    category: "Appliances",
    rating: 4.2,
    ratingCount: 7100,
    price: 5499,
    originalPrice: 7500,
    image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=600&q=80",
    description: "Ozone disinfection technology oxidises surface chemicals, bacteria, and pesticides from greens without nutrient loss.",
    bestFor: "Purifying farm vegetables and fruits in city households"
  },
  {
    name: "Crompton Amica 15 Litre 5-Star Storage Water Heater Geyser",
    brand: "Crompton",
    category: "Appliances",
    rating: 4.4,
    ratingCount: 17400,
    price: 6699,
    originalPrice: 11200,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "High precision thermostat with standby cutoff, magnesium sacrificial anode, and powerful 2000W copper element.",
    bestFor: "Hot morning showers with lower power consumption"
  },
  {
    name: "Havells Festiva 1200mm Decorative High Speed Ceiling Fan (Gold Pearl)",
    brand: "Havells",
    category: "Appliances",
    rating: 4.3,
    ratingCount: 14900,
    price: 2699,
    originalPrice: 4290,
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=600&q=80",
    description: "Metallic paint finish with decorative blade trims, 390 RPM motor, and wide tip blades for broad breeze dispersion.",
    bestFor: "Living room elegance and high air throw in summer"
  },
  {
    name: "Bajaj DX 7 1000W Lightweight Dry Iron with Golden American Heritage Coating",
    brand: "Bajaj",
    category: "Appliances",
    rating: 4.3,
    ratingCount: 32600,
    price: 849,
    originalPrice: 1250,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "Lightweight 750g iron with 360-degree swivel cord, thermal safety fuse, and cool-touch handle.",
    bestFor: "Fast wrinkle removal on everyday casuals and office wear"
  },
  {
    name: "Wipro Garnet 20W LED Batten Tube Light 6500K Cool Day Light (Pack of 2)",
    brand: "Wipro",
    category: "Lighting",
    rating: 4.4,
    ratingCount: 23800,
    price: 499,
    originalPrice: 900,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
    description: "2000 lumens high brightness with surge protection up to 4kV and energy efficient driver.",
    bestFor: "Study rooms, kitchens, and garage illumination"
  },
  {
    name: "Solimo Smart B22 12W LED WiFi Colour Changing Bulb",
    brand: "Solimo",
    category: "Lighting",
    rating: 4.2,
    ratingCount: 18400,
    price: 549,
    originalPrice: 1499,
    image: "https://images.unsplash.com/photo-1550985616-10810253b84d?auto=format&fit=crop&w=600&q=80",
    description: "Voice-controlled smart bulb compatible with Alexa & Google Assistant with timer schedules.",
    bestFor: "Dimming bedside lamps without getting out of bed"
  },
  {
    name: "Home Centre Mosaic Glass Ceiling Pendant Hanging Light (Brass)",
    brand: "Home Centre",
    category: "Lighting",
    rating: 4.4,
    ratingCount: 4600,
    price: 1599,
    originalPrice: 3299,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
    description: "Handcrafted mosaic glass pendant light that casts amber decorative patterns on dining tables.",
    bestFor: "Dining room tables, kitchen breakfast counters, and balcony lounges"
  },
  {
    name: "Stanley 24-Piece 1/2-Inch Drive Metric Socket Ratchet Set",
    brand: "Stanley",
    category: "Tools",
    rating: 4.6,
    ratingCount: 8200,
    price: 2899,
    originalPrice: 4200,
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80",
    description: "Quick-release ratchet mechanism with chrome-vanadium sockets from 10mm to 32mm and extension bar.",
    bestFor: "Car wheel nuts, bicycle repairs, and machinery tightening"
  },
  {
    name: "Taparia 6-inch Long Nose Plier with Side Cutter (1421-6)",
    brand: "Taparia",
    category: "Tools",
    rating: 4.5,
    ratingCount: 14300,
    price: 299,
    originalPrice: 390,
    image: "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=600&q=80",
    description: "Precision knurled jaw tips reach into confined junction boxes with induction hardened cutting blades.",
    bestFor: "Electrical socket wiring, jewellery making, and craft hobby work"
  },
  {
    name: "Bosch 33-Piece X-Line Screwdriver Bit and Masonry Drill Set",
    brand: "Bosch",
    category: "Tools",
    rating: 4.4,
    ratingCount: 22600,
    price: 999,
    originalPrice: 1500,
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80",
    description: "Universal magnetic bit holder with Phillips, Torx, Hex, and concrete masonry drill bits in compact hard case.",
    bestFor: "All standard home DIY drilling and screw fixing tasks"
  },
  {
    name: "Kuber Industries 6-Pocket Hanging Handbag and Purse Closet Organizer",
    brand: "Kuber Industries",
    category: "Storage",
    rating: 4.3,
    ratingCount: 8600,
    price: 349,
    originalPrice: 699,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "Transparent PVC slots protect expensive leather purses from crushing and dust inside cupboards.",
    bestFor: "Handbags, clutched wallets, and scarf storage"
  },
  {
    name: "Solimo Under-Shelf Hanging Wire Storage Basket (Pack of 2)",
    brand: "Solimo",
    category: "Storage",
    rating: 4.3,
    ratingCount: 11500,
    price: 499,
    originalPrice: 999,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80",
    description: "White coated steel wire baskets slide onto pantry shelves without tools, instantly adding under-shelf capacity.",
    bestFor: "Holding bread, spices, cling wraps, and mugs in kitchen cupboards"
  },
  {
    name: "Plantex Brass Wall Mounted Bathroom Glass Shelf 18-inch (Heavy 8mm Glass)",
    brand: "Plantex",
    category: "Bathroom",
    rating: 4.4,
    ratingCount: 9100,
    price: 849,
    originalPrice: 1699,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Frosted toughened 8mm safety glass with solid brass railing preventing bottles from slipping off.",
    bestFor: "Under mirror shelf for toothbrushes, shaving foam, and perfumes"
  },
  {
    name: "Kohler Statement Round Single-Function Overhead Rain Showerhead",
    brand: "Kohler",
    category: "Bathroom",
    rating: 4.5,
    ratingCount: 6200,
    price: 2499,
    originalPrice: 3800,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Full coverage rain spray with MasterClean sprayface that resists hard water scale buildup.",
    bestFor: "Drenching spa rain showers in master bathrooms"
  },
  {
    name: "Saral Home Striped Anti-Skid Cotton Bathroom Floor Mat (40x60cm)",
    brand: "Saral Home",
    category: "Bathroom",
    rating: 4.4,
    ratingCount: 13800,
    price: 299,
    originalPrice: 599,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "100% natural cotton tufted surface with non-slip spray latex back that absorbs water instantly.",
    bestFor: "Stepping out from bath tubs and shower glass doors"
  },
  {
    name: "Plantex Stainless Steel Wall Mounted Toothbrush Holder with Tumbler",
    brand: "Plantex",
    category: "Bathroom",
    rating: 4.4,
    ratingCount: 10400,
    price: 449,
    originalPrice: 850,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    description: "Grade 304 stainless steel bracket holding 4 toothbrushes, 1 toothpaste tube, and frosted glass rinsing tumbler.",
    bestFor: "Clean washbasin vanity organization with zero water pooling"
  }
];

// Enrich with deterministic IDs and verified search URLs
const products = PRODUCTS_DATA.map((p, idx) => {
  const num = (idx + 1).toString().padStart(3, '0');
  const encodedQuery = encodeURIComponent(p.name);
  return {
    id: `prod-${num}`,
    name: p.name,
    brand: p.brand,
    category: p.category,
    rating: p.rating,
    ratingCount: p.ratingCount,
    price: p.price,
    originalPrice: p.originalPrice,
    currency: "INR",
    image: p.image,
    description: p.description,
    bestFor: p.bestFor,
    amazonUrl: `https://www.amazon.in/s?k=${encodedQuery}`,
    flipkartUrl: `https://www.flipkart.com/search?q=${encodedQuery}`,
    availability: "Available"
  };
});

const fileContent = `/**
 * Lokha Home Essentials & Recommended Products Database
 * 
 * Curated collection of ${products.length} highly rated household products,
 * kitchen appliances, cleaning gear, and home improvement tools.
 * 
 * Architecture ready for future live API or Firebase backend integration.
 */

export const PRODUCTS = ${JSON.stringify(products, null, 2)};

export const PRODUCT_CATEGORIES = [
  "All",
  "Kitchen",
  "Cleaning",
  "Home",
  "Appliances",
  "Lighting",
  "Tools",
  "Storage",
  "Bathroom"
];

export const RATING_FILTER_OPTIONS = [
  { label: "All Ratings", value: 0 },
  { label: "4.0+ Stars (Popular)", value: 4.0 },
  { label: "4.2+ Stars (Strong)", value: 4.2 },
  { label: "4.5+ Stars (Excellent)", value: 4.5 }
];

export const REVIEW_VOLUME_OPTIONS = [
  { label: "All Reviews", value: 0 },
  { label: "1,000+ Reviews", value: 1000 },
  { label: "5,000+ Reviews", value: 5000 },
  { label: "10,000+ Reviews", value: 10000 }
];

export const PRICE_RANGE_OPTIONS = [
  { label: "All Prices", min: 0, max: Infinity },
  { label: "Under ₹500", min: 0, max: 500 },
  { label: "₹500–₹1,000", min: 500, max: 1000 },
  { label: "₹1,000–₹5,000", min: 1000, max: 5000 },
  { label: "₹5,000–₹15,000", min: 5000, max: 15000 },
  { label: "₹15,000+", min: 15000, max: Infinity }
];

export const SORT_OPTIONS = [
  { label: "Recommended", value: "recommended" },
  { label: "Highest Rated", value: "rating_high" },
  { label: "Most Reviewed", value: "reviews_high" },
  { label: "Price: Low to High", value: "price_low" },
  { label: "Price: High to Low", value: "price_high" },
  { label: "Biggest Discount", value: "discount_high" }
];
`;

const outputPath = path.resolve(__dirname, '../src/data/products.js');
fs.writeFileSync(outputPath, fileContent, 'utf-8');
console.log(`Generated ${products.length} products to ${outputPath}`);
